spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  second-datasource:
      url: jdbc:h2:mem:second-testdb
      driverClassName: org.h2.Driver
      username: sa2
      password: password2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  first-liquibase:
    change-log: classpath:/db/changelog/first/db.changelog-master.yaml
  second-liquibase:
    change-log: classpath:/db/changelog/second/db.changelog-master.yaml